services:
  holobot:
    image: ghcr.io/adrmrt/holobot:${IMAGE_TAG:-latest}
    container_name: holobot
    env_file:
      - .env
    environment:
      TZ: Europe/Zurich
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped